name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.7"

        - name: Install uv
          uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3

        - name: Set up Python
          run: uv python install 3.11

        - name: Install the project
          run: uv sync --all-extras --dev

        - name: "Run ruff"
          run: uv run ruff check .

        - name: "Format with ruff"
          run: uv run ruff format . --check
